/**
 * Message Types for Extension Communication
 * Shared between content script, background worker, and offscreen document
 */

export const MessageTypes = {
  // AI Service Messages
  AI_CONFIGURE: 'AI_CONFIGURE',
  AI_IS_CONFIGURED: 'AI_IS_CONFIGURED',
  AI_SEND_MESSAGE: 'AI_SEND_MESSAGE',
  AI_SEND_MESSAGE_STREAM: 'AI_SEND_MESSAGE_STREAM',
  AI_STREAM_TOKEN: 'AI_STREAM_TOKEN', // Streaming token from background to content
  AI_ABORT: 'AI_ABORT',
  AI_IS_GENERATING: 'AI_IS_GENERATING',
  AI_TEST_CONNECTION: 'AI_TEST_CONNECTION',
  
  // Chrome AI Validator Messages
  CHROME_AI_CHECK_AVAILABILITY: 'CHROME_AI_CHECK_AVAILABILITY',
  CHROME_AI_IS_SUPPORTED: 'CHROME_AI_IS_SUPPORTED',
  CHROME_AI_START_DOWNLOAD: 'CHROME_AI_START_DOWNLOAD',
  CHROME_AI_DOWNLOAD_PROGRESS: 'CHROME_AI_DOWNLOAD_PROGRESS',
  
  // TTS Service Messages
  TTS_CONFIGURE: 'TTS_CONFIGURE',
  TTS_IS_CONFIGURED: 'TTS_IS_CONFIGURED',
  TTS_GENERATE_SPEECH: 'TTS_GENERATE_SPEECH',
  TTS_PROCESS_AUDIO_WITH_LIPSYNC: 'TTS_PROCESS_AUDIO_WITH_LIPSYNC',
  TTS_STOP_PLAYBACK: 'TTS_STOP_PLAYBACK',
  TTS_RESUME_PLAYBACK: 'TTS_RESUME_PLAYBACK',
  TTS_STOP_GENERATION: 'TTS_STOP_GENERATION',
  TTS_RESUME_GENERATION: 'TTS_RESUME_GENERATION',
  TTS_GET_QUEUE_LENGTH: 'TTS_GET_QUEUE_LENGTH',
  TTS_IS_PLAYING: 'TTS_IS_PLAYING',
  TTS_TEST_CONNECTION: 'TTS_TEST_CONNECTION',
  
  // Kokoro TTS Messages
  KOKORO_INIT: 'KOKORO_INIT',
  KOKORO_GENERATE: 'KOKORO_GENERATE',
  KOKORO_CHECK_STATUS: 'KOKORO_CHECK_STATUS',
  KOKORO_DOWNLOAD_PROGRESS: 'KOKORO_DOWNLOAD_PROGRESS',
  KOKORO_LIST_VOICES: 'KOKORO_LIST_VOICES',
  KOKORO_PING: 'KOKORO_PING',
  KOKORO_GET_CACHE_SIZE: 'KOKORO_GET_CACHE_SIZE',
  KOKORO_CLEAR_CACHE: 'KOKORO_CLEAR_CACHE',
  
  // STT Service Messages
  STT_CONFIGURE: 'STT_CONFIGURE',
  STT_IS_CONFIGURED: 'STT_IS_CONFIGURED',
  STT_START_RECORDING: 'STT_START_RECORDING',
  STT_STOP_RECORDING: 'STT_STOP_RECORDING',
  STT_TRANSCRIBE_AUDIO: 'STT_TRANSCRIBE_AUDIO',
  STT_TEST_RECORDING: 'STT_TEST_RECORDING',
  
  // Translator Service Messages
  TRANSLATOR_CONFIGURE: 'TRANSLATOR_CONFIGURE',
  TRANSLATOR_IS_CONFIGURED: 'TRANSLATOR_IS_CONFIGURED',
  TRANSLATOR_CHECK_AVAILABILITY: 'TRANSLATOR_CHECK_AVAILABILITY',
  TRANSLATOR_TRANSLATE: 'TRANSLATOR_TRANSLATE',
  TRANSLATOR_TRANSLATE_STREAMING: 'TRANSLATOR_TRANSLATE_STREAMING',
  TRANSLATOR_ABORT: 'TRANSLATOR_ABORT',
  TRANSLATOR_DESTROY: 'TRANSLATOR_DESTROY',
  
  // Language Detector Service Messages
  LANGUAGE_DETECTOR_CONFIGURE: 'LANGUAGE_DETECTOR_CONFIGURE',
  LANGUAGE_DETECTOR_IS_CONFIGURED: 'LANGUAGE_DETECTOR_IS_CONFIGURED',
  LANGUAGE_DETECTOR_CHECK_AVAILABILITY: 'LANGUAGE_DETECTOR_CHECK_AVAILABILITY',
  LANGUAGE_DETECTOR_DETECT: 'LANGUAGE_DETECTOR_DETECT',
  LANGUAGE_DETECTOR_DESTROY: 'LANGUAGE_DETECTOR_DESTROY',
  
  // Summarizer Service Messages
  SUMMARIZER_CONFIGURE: 'SUMMARIZER_CONFIGURE',
  SUMMARIZER_IS_CONFIGURED: 'SUMMARIZER_IS_CONFIGURED',
  SUMMARIZER_CHECK_AVAILABILITY: 'SUMMARIZER_CHECK_AVAILABILITY',
  SUMMARIZER_SUMMARIZE: 'SUMMARIZER_SUMMARIZE',
  SUMMARIZER_SUMMARIZE_STREAMING: 'SUMMARIZER_SUMMARIZE_STREAMING',
  SUMMARIZER_ABORT: 'SUMMARIZER_ABORT',
  SUMMARIZER_DESTROY: 'SUMMARIZER_DESTROY',
  
  // Rewriter Service Messages
  REWRITER_CONFIGURE: 'REWRITER_CONFIGURE',
  REWRITER_IS_CONFIGURED: 'REWRITER_IS_CONFIGURED',
  REWRITER_CHECK_AVAILABILITY: 'REWRITER_CHECK_AVAILABILITY',
  REWRITER_REWRITE: 'REWRITER_REWRITE',
  REWRITER_REWRITE_STREAMING: 'REWRITER_REWRITE_STREAMING',
  REWRITER_ABORT: 'REWRITER_ABORT',
  REWRITER_DESTROY: 'REWRITER_DESTROY',
  
  // Writer Service Messages
  WRITER_CONFIGURE: 'WRITER_CONFIGURE',
  WRITER_IS_CONFIGURED: 'WRITER_IS_CONFIGURED',
  WRITER_CHECK_AVAILABILITY: 'WRITER_CHECK_AVAILABILITY',
  WRITER_WRITE: 'WRITER_WRITE',
  WRITER_WRITE_STREAMING: 'WRITER_WRITE_STREAMING',
  WRITER_ABORT: 'WRITER_ABORT',
  WRITER_DESTROY: 'WRITER_DESTROY',
  
  // VMD/BVMD Service Messages
  VMD_GENERATE: 'VMD_GENERATE',
  BVMD_CONVERT: 'BVMD_CONVERT',

  // Storage Messages - CONFIG namespace
  STORAGE_CONFIG_SAVE: 'STORAGE_CONFIG_SAVE',
  STORAGE_CONFIG_LOAD: 'STORAGE_CONFIG_LOAD',
  STORAGE_CONFIG_EXISTS: 'STORAGE_CONFIG_EXISTS',
  STORAGE_CONFIG_REMOVE: 'STORAGE_CONFIG_REMOVE',
  STORAGE_CONFIG_GET_ALL: 'STORAGE_CONFIG_GET_ALL',
  STORAGE_CONFIG_CLEAR: 'STORAGE_CONFIG_CLEAR',

  // Storage Messages - SETTINGS namespace
  STORAGE_SETTINGS_SAVE: 'STORAGE_SETTINGS_SAVE',
  STORAGE_SETTINGS_LOAD: 'STORAGE_SETTINGS_LOAD',
  STORAGE_SETTINGS_EXISTS: 'STORAGE_SETTINGS_EXISTS',
  STORAGE_SETTINGS_REMOVE: 'STORAGE_SETTINGS_REMOVE',
  STORAGE_SETTINGS_GET_ALL: 'STORAGE_SETTINGS_GET_ALL',
  STORAGE_SETTINGS_CLEAR: 'STORAGE_SETTINGS_CLEAR',

  // Storage Messages - CACHE namespace
  STORAGE_CACHE_SAVE: 'STORAGE_CACHE_SAVE',
  STORAGE_CACHE_LOAD: 'STORAGE_CACHE_LOAD',
  STORAGE_CACHE_EXISTS: 'STORAGE_CACHE_EXISTS',
  STORAGE_CACHE_REMOVE: 'STORAGE_CACHE_REMOVE',
  STORAGE_CACHE_GET_ALL: 'STORAGE_CACHE_GET_ALL',
  STORAGE_CACHE_CLEANUP: 'STORAGE_CACHE_CLEANUP',
  STORAGE_CACHE_CLEAR: 'STORAGE_CACHE_CLEAR',

  // Storage Messages - CHAT namespace
  STORAGE_CHAT_SAVE: 'STORAGE_CHAT_SAVE',
  STORAGE_CHAT_LOAD: 'STORAGE_CHAT_LOAD',
  STORAGE_CHAT_EXISTS: 'STORAGE_CHAT_EXISTS',
  STORAGE_CHAT_REMOVE: 'STORAGE_CHAT_REMOVE',
  STORAGE_CHAT_GET_ALL: 'STORAGE_CHAT_GET_ALL',
  STORAGE_CHAT_CLEAR: 'STORAGE_CHAT_CLEAR',

  // Storage Messages - FILE namespace
  STORAGE_FILE_SAVE: 'STORAGE_FILE_SAVE',
  STORAGE_FILE_LOAD: 'STORAGE_FILE_LOAD',
  STORAGE_FILE_EXISTS: 'STORAGE_FILE_EXISTS',
  STORAGE_FILE_REMOVE: 'STORAGE_FILE_REMOVE',
  STORAGE_FILES_GET_ALL: 'STORAGE_FILES_GET_ALL',
  STORAGE_FILES_GET_BY_CATEGORY: 'STORAGE_FILES_GET_BY_CATEGORY',
  STORAGE_FILES_GET_METADATA_BY_CATEGORY: 'STORAGE_FILES_GET_METADATA_BY_CATEGORY',
  STORAGE_FILES_CLEAR: 'STORAGE_FILES_CLEAR',

  // Storage Messages - DATA namespace
  STORAGE_DATA_SAVE: 'STORAGE_DATA_SAVE',
  STORAGE_DATA_LOAD: 'STORAGE_DATA_LOAD',
  STORAGE_DATA_EXISTS: 'STORAGE_DATA_EXISTS',
  STORAGE_DATA_REMOVE: 'STORAGE_DATA_REMOVE',
  STORAGE_DATA_GET_ALL: 'STORAGE_DATA_GET_ALL',
  STORAGE_DATA_GET_BY_CATEGORY: 'STORAGE_DATA_GET_BY_CATEGORY',
  STORAGE_DATA_CLEAR: 'STORAGE_DATA_CLEAR',

  // Storage Messages - UTILITY
  STORAGE_GET_STATS: 'STORAGE_GET_STATS',
  STORAGE_CLEAR_ALL: 'STORAGE_CLEAR_ALL',
  
  // Legacy Storage Messages (kept for compatibility)
  STORAGE_GET: 'STORAGE_GET',
  STORAGE_SET: 'STORAGE_SET',
  STORAGE_REMOVE: 'STORAGE_REMOVE',
  STORAGE_CLEAR: 'STORAGE_CLEAR',
  
  // Offscreen Document Messages
  OFFSCREEN_AUDIO_PROCESS: 'OFFSCREEN_AUDIO_PROCESS',
  OFFSCREEN_AUDIO_PLAY: 'OFFSCREEN_AUDIO_PLAY',
  OFFSCREEN_AUDIO_STOP: 'OFFSCREEN_AUDIO_STOP',
  OFFSCREEN_VMD_GENERATE: 'OFFSCREEN_VMD_GENERATE',
  
  // Streaming Events
  STREAM_CHUNK: 'STREAM_CHUNK',
  STREAM_END: 'STREAM_END',
  STREAM_ERROR: 'STREAM_ERROR',
  
  // Tab Management
  TAB_INIT: 'TAB_INIT',
  TAB_CLEANUP: 'TAB_CLEANUP',
  TAB_STATE_UPDATE: 'TAB_STATE_UPDATE',
  
  // Response Types
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  PROGRESS: 'PROGRESS'
};

export const MessagePriority = {
  HIGH: 0,
  NORMAL: 1,
  LOW: 2
};

/**
 * Create a message with proper structure
 */
export function createMessage(type, data = {}, options = {}) {
  return {
    type,
    data,
    requestId: options.requestId || generateRequestId(),
    tabId: options.tabId || null,
    timestamp: Date.now(),
    priority: options.priority || MessagePriority.NORMAL
  };
}

/**
 * Create a response message
 */
export function createResponse(requestId, data = {}, success = true) {
  return {
    type: success ? MessageTypes.SUCCESS : MessageTypes.ERROR,
    requestId,
    data,
    timestamp: Date.now()
  };
}

/**
 * Generate unique request ID
 */
export function generateRequestId() {
  return `${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}
