export {
  createVAssistShadowRootMount,
  defineVAssistEmbedElement,
  injectVAssistEmbed,
  removeVAssistEmbed,
  updateVAssistEmbedConfig,
} from "../../../embed/main";

export {
  DEFAULT_VASSIST_EMBED_HOST_ID,
  mergeVAssistEmbedConfig,
  normalizeVAssistEmbedConfig,
  type DeepPartial,
  type ResolvedVAssistEmbedConfig,
  type VAssistEmbedApi,
  type VAssistEmbedConfig,
  type VAssistEmbedElementHandle,
  type VAssistEmbedHooks,
  type VAssistEmbedInjectOptions,
  type VAssistFeatureName,
  type VAssistMessageEventPayload,
  type VAssistProviderMode,
  type VAssistResourceLoader,
  type VAssistRuntimeIsolationMode,
  type VAssistThemeConfig,
  type VAssistThemeEffects,
  type VAssistThemeMode,
  type VAssistSettingsTabId,
  type VAssistShellMode,
  type VAssistStorageAdapter,
  type VAssistStorageMode,
  type VAssistThemeSurfaceStyle,
  type VAssistThemeTokens,
  type VAssistTransportMode,
} from "../../../src/embed/config";

export {
  createStorageManager,
  createMemoryStorageAdapter,
  DexieStorageAdapter,
  MemoryStorageAdapter,
  getDefaultStorageAdapter,
  getRegisteredStorageAdapter,
  listRegisteredStorageAdapters,
  registerStorageAdapter,
  resolveStorageAdapter,
  setDefaultStorageAdapter,
  type StorageAdapterLike,
  type StorageAdapterSelection,
  type StorageMetadata,
  type StorageRecord,
  type StorageStats,
  type StorageTableName,
} from "../../../src/storage";

export {
  DefaultResourceLoader,
  builtinResourceLoader,
  getRegisteredResourceLoader,
  listRegisteredResourceLoaders,
  registerResourceLoader,
  resolveResourceLoader,
  resourceLoader,
  setDefaultResourceLoader,
  type ResourceLoaderAdapterLike,
  type ResourceLoaderSelection,
} from "../../../src/utils/ResourceLoader";
