export {
  createVAssistShadowRootMount,
  defineVAssistEmbedElement,
  injectVAssistEmbed,
  removeVAssistEmbed,
  updateVAssistEmbedConfig,
} from "../../../embed/main";

export {
  DEFAULT_VASSIST_EMBED_HOST_ID,
  mergeVAssistEmbedConfig,
  normalizeVAssistEmbedConfig,
  type DeepPartial,
  type ResolvedVAssistEmbedConfig,
  type VAssistBinaryLike,
  type VAssistBrandingConfig,
  type VAssistEmbedApi,
  type VAssistEmbedConfig,
  type VAssistEmbedElementHandle,
  type VAssistEmbedHooks,
  type VAssistEmbedInjectOptions,
  type VAssistFeatureName,
  type VAssistLabelId,
  type VAssistMessageEventPayload,
  type VAssistOpenSettingsOptions,
  type VAssistPortalContainerId,
  type VAssistPortalContainerTarget,
  type VAssistPortalContainersConfig,
  type VAssistProviderBridge,
  type VAssistProviderBridgeAI,
  type VAssistProviderBridgeSTT,
  type VAssistProviderBridgeTTS,
  type VAssistProviderMode,
  type VAssistResourceLoader,
  type VAssistRuntimeIsolationMode,
  type VAssistRuntimeSnapshot,
  type VAssistRuntimeSnapshotMessage,
  type VAssistSendMessageInput,
  type VAssistSetDraftOptions,
  type VAssistSettingsFieldId,
  type VAssistSettingsPolicy,
  type VAssistSettingsSectionId,
  type VAssistSettingsSubTabId,
  type VAssistThemeConfig,
  type VAssistThemeEffects,
  type VAssistThemeMode,
  type VAssistSettingsTabId,
  type VAssistSettingsTargetId,
  type VAssistShellMode,
  type VAssistStorageAdapter,
  type VAssistStorageMode,
  type VAssistThemeSurfaceStyle,
  type VAssistThemeTokens,
  type VAssistToolbarActionId,
  type VAssistTransportMode,
  type VAssistTriggerToolbarActionOptions,
} from "../../../src/embed/config";

export {
  createStorageManager,
  createMemoryStorageAdapter,
  DexieStorageAdapter,
  MemoryStorageAdapter,
  getDefaultStorageAdapter,
  getRegisteredStorageAdapter,
  listRegisteredStorageAdapters,
  registerStorageAdapter,
  resolveStorageAdapter,
  setDefaultStorageAdapter,
  type StorageAdapterLike,
  type StorageAdapterSelection,
  type StorageMetadata,
  type StorageRecord,
  type StorageStats,
  type StorageTableName,
} from "../../../src/storage";

export {
  DefaultResourceLoader,
  builtinResourceLoader,
  getRegisteredResourceLoader,
  listRegisteredResourceLoaders,
  registerResourceLoader,
  resolveResourceLoader,
  resourceLoader,
  setDefaultResourceLoader,
  type ResourceLoaderAdapterLike,
  type ResourceLoaderSelection,
} from "../../../src/utils/ResourceLoader";
