/**
 * Icon Map - Heroicons (Professional Icon Library by Tailwind)
 * Maps icon names to Heroicons solid (filled) components
 */

import * as HeroIconsSolid from '@heroicons/react/24/solid';
import * as HeroIconsOutline from '@heroicons/react/24/outline';

// Map custom icon names to Heroicons components (using solid/filled by default)
export const iconMap = {
  'close': HeroIconsSolid.XMarkIcon,
  'stop': HeroIconsSolid.StopIcon,
  'pause': HeroIconsSolid.PauseIcon,
  'play': HeroIconsSolid.PlayIcon,
  'record': HeroIconsSolid.StopCircleIcon,
  'check': HeroIconsSolid.CheckIcon,
  'error': HeroIconsSolid.XCircleIcon,
  'attachment': HeroIconsSolid.PaperClipIcon,
  'clipboard': HeroIconsSolid.ClipboardIcon,
  'edit': HeroIconsSolid.PencilIcon,
  'write': HeroIconsSolid.PencilSquareIcon,
  'delete': HeroIconsSolid.TrashIcon,
  'refresh': HeroIconsSolid.ArrowPathIcon,
  'regenerate': HeroIconsSolid.ArrowPathIcon,
  'add': HeroIconsSolid.PlusIcon,
  'loading': HeroIconsOutline.ArrowPathIcon,
  'success': HeroIconsSolid.CheckCircleIcon,
  'error-status': HeroIconsSolid.XCircleIcon,
  'warning': HeroIconsSolid.ExclamationTriangleIcon,
  'info': HeroIconsSolid.InformationCircleIcon,
  'download': HeroIconsSolid.ArrowDownTrayIcon,
  'volume': HeroIconsSolid.SpeakerWaveIcon,
  'chat': HeroIconsSolid.ChatBubbleLeftIcon,
  'send': HeroIconsSolid.PaperAirplaneIcon,
  'microphone': HeroIconsSolid.MicrophoneIcon,
  'speaker': HeroIconsSolid.SpeakerWaveIcon,
  'phone': HeroIconsSolid.PhoneIcon,
  'image': HeroIconsSolid.PhotoIcon,
  'music': HeroIconsSolid.MusicalNoteIcon,
  'document': HeroIconsSolid.DocumentIcon,
  'note': HeroIconsSolid.DocumentTextIcon,
  'article': HeroIconsSolid.NewspaperIcon,
  'book': HeroIconsSolid.BookOpenIcon,
  'happy': HeroIconsSolid.FaceSmileIcon,
  'thinking': HeroIconsSolid.QuestionMarkCircleIcon,
  'calm': HeroIconsSolid.FaceSmileIcon,
  'eye': HeroIconsSolid.EyeIcon,
  'eye-off': HeroIconsSolid.EyeSlashIcon,
  'wave': HeroIconsSolid.HandRaisedIcon,
  'globe': HeroIconsSolid.GlobeAltIcon,
  'search': HeroIconsSolid.MagnifyingGlassIcon,
  'key': HeroIconsSolid.KeyIcon,
  'magic': HeroIconsSolid.SparklesIcon,
  'tag': HeroIconsSolid.TagIcon,
  'settings': HeroIconsSolid.Cog6ToothIcon,
  'tools': HeroIconsSolid.WrenchScrewdriverIcon,
  'wrench': HeroIconsSolid.WrenchIcon,
  'stats': HeroIconsSolid.ChartBarIcon,
  'arrow-up': HeroIconsSolid.ArrowUpIcon,
  'arrow-down': HeroIconsSolid.ArrowDownIcon,
  'arrow-left': HeroIconsSolid.ArrowLeftIcon,
  'arrow-right': HeroIconsSolid.ArrowRightIcon,
  'undo': HeroIconsSolid.ArrowUturnLeftIcon,
  'redo': HeroIconsSolid.ArrowUturnRightIcon,
  'bidirectional': HeroIconsSolid.ArrowsRightLeftIcon,
  'walking': HeroIconsSolid.UserIcon,
  'meditation': HeroIconsSolid.UserIcon,
  'theater': HeroIconsSolid.FaceSmileIcon,
  'celebrate': HeroIconsSolid.SparklesIcon,
  'idea': HeroIconsSolid.LightBulbIcon,
  'target': HeroIconsSolid.CursorArrowRippleIcon,
  'briefcase': HeroIconsSolid.BriefcaseIcon,
  'pin': HeroIconsSolid.MapPinIcon,
  'star': HeroIconsSolid.StarIcon,
  'location': HeroIconsSolid.MapPinIcon,
  'empty': HeroIconsSolid.InboxIcon,
  'save': HeroIconsSolid.ArrowDownTrayIcon,
  'history': HeroIconsSolid.ClockIcon,
  'hand-stop': HeroIconsSolid.HandRaisedIcon,
  'lightning': HeroIconsSolid.BoltIcon,
  'shuffle': HeroIconsSolid.ArrowsRightLeftIcon,
  'question': HeroIconsSolid.QuestionMarkCircleIcon,
  'formal': HeroIconsSolid.UserIcon,
  'sleeping': HeroIconsSolid.MoonIcon,
  'eyes': HeroIconsSolid.EyeIcon,
  'yawn': HeroIconsSolid.FaceSmileIcon,
  'surprised': HeroIconsSolid.FaceSmileIcon,
  'excited': HeroIconsSolid.SparklesIcon,
  'pencil': HeroIconsSolid.PencilIcon,
  'hourglass': HeroIconsOutline.ArrowPathIcon,
  'checkmark': HeroIconsSolid.CheckIcon,
  'xmark': HeroIconsSolid.XMarkIcon,
  'arrow-top-right': HeroIconsSolid.ArrowUpRightIcon,
  'arrow-top-left': HeroIconsSolid.ArrowUpLeftIcon,
  'arrow-bottom-right': HeroIconsSolid.ArrowDownRightIcon,
  'arrow-bottom-left': HeroIconsSolid.ArrowDownLeftIcon,
  'spinner': HeroIconsOutline.ArrowPathIcon,
  'ai': HeroIconsSolid.SparklesIcon,
  'language': HeroIconsSolid.LanguageIcon,
  'file-text': HeroIconsSolid.DocumentTextIcon,
  'pen': HeroIconsSolid.PencilIcon,
  'check-circle': HeroIconsSolid.CheckCircleIcon,
  'move': HeroIconsSolid.ArrowsPointingOutIcon,
  'maximize': HeroIconsSolid.ArrowsPointingOutIcon,
  'user': HeroIconsSolid.UserIcon,
  'message-circle': HeroIconsSolid.ChatBubbleLeftIcon,
  'arrow-down-right': HeroIconsSolid.ArrowDownRightIcon,
  'arrow-down-left': HeroIconsSolid.ArrowDownLeftIcon,
  'arrow-up-right': HeroIconsSolid.ArrowUpRightIcon,
  'arrow-up-left': HeroIconsSolid.ArrowUpLeftIcon,
  'map-pin': HeroIconsSolid.MapPinIcon,
  'shield': HeroIconsSolid.ShieldCheckIcon,
  'mic': HeroIconsSolid.MicrophoneIcon,
  'sparkles': HeroIconsSolid.SparklesIcon,
  'cpu': HeroIconsSolid.CpuChipIcon,
  'flag': HeroIconsSolid.FlagIcon,
  'copy': HeroIconsSolid.DocumentDuplicateIcon,
};

export default iconMap;
